.TH client 1 "15 December 2017" "Version 1.0"
.SH NAME
client \- Envoi un hash a un serveur ou permet de recuperer les ip associes a un hash.
.SH SYNOPSIS
.B client 
ip_serv port_serv 
.I OPTION
hash [ip_hash]
.SH DESCRIPTION
.B client 
permet d'envoyer un hash associé a une ip ou de recuperer les ip associées a un 
hash sur un serveur distant.
.SH OPTIONS
.IP get
.B demande
les 
.B ip 
associés au 
.I hash
au 
.B serveur distant (
.I ip_serv port_serv
)
.IP put
permet d'envoyer un 
.I hash 
et l'
.I ip_hash 
associée au hash a un serveur distant (
.I ip_serv port_serv
)
.IP exit
permet de 
.B stopper un serveur distant
.I ip_serv port_serv
en tappant le 
.B mot de passe ( 
.I hash
)
.SH DIAGNOSTICS
." Messages d'erreurs courants
.SH BUGS
." Bugs eventuels
.SH AUTHORS
.PP
David Lardenois dlardenois@etu.unistra.fr 
.PP
Lionel Jung	lionel.jung@etu.unistra.fr
.SH "SEE ALSO"
.BR socket ,
.BR sendto , 
.BR recvfrom ,
.BR select ,

