.TH SERVER 1 "15 Decembre 2017" "Version 1.0"
.SH NOM
SERVER \- Permet de creer un serveur ipv6 gerant une table de hash partagee.
.SH SYNOPSIS
.B server
ip port [
.I \-c
ip_d port_d ]
.SH DESCRIPTION
.PP
Le programme
.B server
est creer avec une 
.I ip
et un
.IR port .
.PP
Une fois cree il
.B poura recevoir des hash 
envoyes par des clients et il les stockera dans une table de hash.
.PP 
Il poura aussi 
.B recevoir 
des 
.B demandes de hash 
ou il 
.B envera la liste des ip associes 
au hash au client si le hash existe dans la table;
.SH OPTIONS
.IP \-c
.B Se connecte a un autre serveur 
dont on precisera son
.I ip_d
et son
.IR port_d . 
.SH DIAGNOSTICS
." Messages d'erreurs courants
Les messages d'erreurs suivant sont susceptibles d'etre affichées sur stderr:

Port invalide.
.RS
Le 
.B port 
doit avoir une 
.B valeure 
comprise 
.B entre 0
et
.B 655536.
.RE

Option inconnue
.RS
L'option n'est pas 
.IR -c .
.RE

Ip invalide
.RS
L'ip entree n'est pas une ipv6.
.RE

Erreur conversion ip
.RS
L'ip n'etait pas une ipv6 ou ce n'etait pas une ip valide.
.RE

Not enough space for new connexion
.RS
On a ateint le nombre maximum de connexion autorisés.
.RE

NO ANSWER FROM SERVER
.RS
Le serveur n'a pas repondu dans les temps ou le serveur demande n'exite pas.
.RE
.SH EXEMPLE
.PP
.B Exemple demmarage
 \- l'ip du serveur est ::1
 \- le port du serveur est 9999

Commande: 
.B ./server
::1 9999

Resultat : Le serveur est operationnel

.B Exemple -c:
 \- l'ip qu'on veut donner au serveur est ::2
 \- le port que l'on veut donner au serveur est 9887
 \- l'ip du serveur dest est ::1
 \- le port du serveur dest est 9999

Commande:
.B ./server
::2 9887 -c ::1 9997

Resultat: Le serveur est operationnel
.SH CODES DE RETOUR
.TI
.B client
a les codes de retour suivants:

.TI
.B 0	
Le serveur s'est termine correctement.

.TI
.B 1	
Le serveur s'est arrete suite a une erreur.
.SH BUGS
.SH BUGS
." Bugs eventuels
.PP 
Si on a plus que deux serveurs tourant sur la meme interface il y a des deconnexion intenpestives lies a des ecrasement de message lors de l'envoi.
." autres bugs ?
.PP
C'est l'un des rares bugs que j'ai remarqué, si il y en a d'autres veuillez m'excuser.
.SH AUTEUR
David Lardenois dlardenois@etu.unistra.fr 
